name: Deploy IntelliShelf

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/intellishelf:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/intellishelf:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/intellishelf:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/intellishelf:buildcache,mode=max
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
    # Uncomment and configure the following steps based on your deployment target
    # For example, to deploy to a cloud provider or your own server
    
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    # - name: Push Docker image
    #   run: |
    #     docker tag intellishelf ${{ secrets.DOCKER_HUB_USERNAME }}/intellishelf:latest
    #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/intellishelf:latest
    
    # - name: Deploy to server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     key: ${{ secrets.SERVER_SSH_KEY }}
    #     script: |
    #       cd /path/to/deployment
    #       docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/intellishelf:latest
    #       docker-compose down
    #       docker-compose up -d 